### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by stevecohenfr** [epool/firebase-cloning-tool#2]
On OS X it just open a new chrome session on google login page and nothing append, and after some seconds the program stop with <Unable to find field "Email">

**Comment by epool** [comment]
@stevecohenfr this tool is kinda outdated, probably Google/Firebase has changed updated his ids/class names, please if you have some ruby and capybara knowledge feel free to update the references and PR the changes, otherwise I hope to get some time to fix this issues. In advance thanks!

**Comment by stevecohenfr** [comment]
I do not know ruby but I can learn it fastly.
I will do PR tomorrow.
Thanks

**Comment by epool** [comment]
@stevecohenfr `v0.1.6` should work now, feel free to review #3 to figure out how it was fixed in case you need further changes or the elements get outdated again. Thanks

**Comment by stevecohenfr** [comment]
It still not work :/ 

> Trying sign in for my@mail.com...
Waiting for selector: div.c5e-landing-create-project-button...
Sign in completed.
Opening MyProject project...
Project MyProjectCopy loaded.
Going to remote config...
/Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/node/finders.rb:294:in `block in synced_resolve': Unable to find visible css ".c5e-entry-displayname" with text "Remote Config" (Capybara::ElementNotFound)
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/node/base.rb:83:in `synchronize'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/node/finders.rb:285:in `synced_resolve'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/node/finders.rb:33:in `find'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/session.rb:734:in `block (2 levels) in <class:Session>'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/firebase-cloning-tool-0.1.6/lib/firebase/cloning/tool.rb:83:in `go_to_remote_config'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/firebase-cloning-tool-0.1.6/lib/firebase/cloning/tool.rb:164:in `clone_firebase_remote_config'
	from /Users/steve/.rvm/gems/ruby-2.3.4/gems/firebase-cloning-tool-0.1.6/bin/firebase-cloning-tool:5:in `<top (required)>'
	from /Users/steve/.rvm/gems/ruby-2.3.4/bin/firebase-cloning-tool:23:in `load'
	from /Users/steve/.rvm/gems/ruby-2.3.4/bin/firebase-cloning-tool:23:in `<main>'
	from /Users/steve/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/steve/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'

**Comment by stevecohenfr** [comment]
Ok I just needed i enable Remote config, but it crash later on 

> Pasting remote config from memory...
/Users/steve/.rvm/gems/ruby-2.3.4/gems/capybara-3.3.1/lib/capybara/node/finders.rb:294:in `block in synced_resolve': Unable to find visible xpath "//*[@id=\"main\"]/ng-transclude/div/div/div[2]/r10g-ng2-parameter-list/div/div/mat-card/fire-inline-editor[1]/div/r10g-ng2-parameter-editor/form/div/div[3]/div[2]/button[1]" (Capybara::ElementNotFound)

**Comment by epool** [comment]
@stevecohenfr feel free to clone the project, do the required change/fix for that xpath, run `bundle install` and then `bundle exec rake install` to install the gem locally, with this you can now use `firebase-cloning-tool` locally with your changes, once it works feel free to do a PR with the fix, thank you!
